name: animal_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.17+18

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  get: ^4.1.4
  intro_slider: ^2.4.3
  badges: ^2.0.1
  url_launcher: ^6.0.6

  rxdart: ^0.27.1
  
  equatable: ^2.0.2
  path_provider: ^2.0.2
  # onesignal_flutter: ^2.6.2
  http: ^0.13.3
  intl: ^0.17.0
  flutter_image_compress: ^1.0.0
  
  toast: ^0.1.5
  rflutter_alert: ^2.0.2
  shimmer: ^2.0.0
  onesignal_flutter: ^3.0.0

  # flutter_slidable: ^0.5.7
  # lazy_load_scrollview: ^1.1.0
  responsive_grid: ^2.0.0
  image_picker: ^0.8.0+1
  # time_machine: ^0.9.16

  # flutter_open_whatsapp: ^0.1.2

  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  modal_bottom_sheet: ^2.0.0
  shared_preferences: ^2.0.6
  lottie: ^1.0.1



  
  # geolocator: ^6.1.13
  # onesignal_flutter: ^2.0.0

  # location: ^3.0.0
  # connectivity: ^0.4.9+5
  


  # charts_flutter: ^0.9.0





  

dev_dependencies:
  # flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^1.1.8+4

  build_runner: ^2.0.4

 
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
